name: dart_ddi
description: "A Dependency Injection package, with Qualifier, Decorators, Interceptors and more. Inspired by Java CDI and get_it."
version: 0.1.0
homepage: https://github.com/Willian199/dart_ddi

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
