name: dart_di
description: "A Dependency Injection package, inspired by Java CDI and get_it."
version: 0.0.1
homepage: https://github.com/Willian199/dart-di

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
